import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]


[font]
    normal = {family = "FiraCode Nerd Font", style = "SemiBold"}
    size = 18
    
[window]
    startup_mode = "Maximized"
    opacity = 0.7
    option_as_alt = "OnlyLeft"
    decorations = "None"

[keyboard]
    bindings = [{ key = "T", mods =  "Control | Command",  action =  "SpawnNewInstance"}]

[env]
TERM = "xterm-256color"
